export const SET_LEFT_SIDEBAR = "SET_LEFT_SIDEBAR";
export const TOGGLE_LEFT_SIDEBAR = "TOGGLE_LEFT_SIDEBAR";

export const SET_RIGHT_SIDEBAR = "SET_RIGHT_SIDEBAR";
export const TOGGLE_RIGHT_SIDEBAR = "TOGGLE_RIGHT_SIDEBAR";

export const CLEAR_LAYOUT_REDUCER_STATE = "CLEAR_LAYOUT_REDUCER_STATE";
